server:
  port: 8060

spring:
  datasource:
    name: lifedemo
    url: jdbc:mysql://localhost:3306/group?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
    username: root
    password: 971126
#    # 使用druid数据源
#    driver-class-name: com.mysql.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20
  #thymeleaf start
  mvc:
    #前端解析器配置
    view:
      #给返回的页面添加后缀名，spring boot默认为.html
      suffix: .html
      #定位模板的目录,spring boot此配置默认为classpath:/templates/
      prefix: /templates/
    # 模板引擎
    thymeleaf:
      #模式
      mode: HTML
      #编码格式
      encoding: utf-8
      # 禁用缓存,开启热部署
      cache: false
      #格式
      servlet.content-type: text/html
    #thymeleaf end
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
    profiles:
      active: druid
    # 文件上传
    servlet:
      multipart:
        # 单个文件大小
        max-file-size:  10MB
        # 设置总上传的文件大小
        max-request-size:  20MB
    # 服务模块
    devtools:
      restart:
        # 热部署开关
        enabled: true



## 该配置节点为独立的节点，如将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.lifedemo01.entity  # 注意：对应实体类的路径
#  configuration:
#Mybatis-log打印配置
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #这个是可以打印sql、参数、查询结果的
    #org.apache.ibatis.logging.log4j.Log4jImpl:这个不打印查询结果 cvvv
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

